//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public CATEGORY()
        {
            this.PRODUCTs = new HashSet<PRODUCT>();
        }
    
        public int ID { get; set; }
        public string DisplayName { get; set; }
        public int Quantity { get; set; }
    
        public virtual ICollection<PRODUCT> PRODUCTs { get; set; }
    }
}
