//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystem.Model
{
    using System;
    using System.Collections.Generic;

    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.DEALs = new HashSet<DEAL>();
        }

        public int ID { get; set; }
        public string DisplayName { get; set; }
        public int Quantity { get; set; }
        public int RetailPrice { get; set; }
        public int CatID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual ICollection<DEAL> DEALs { get; set; }
    }
}
